export { default as infoBlock } from './infoBlock'
export { default as heroBlock } from './hero'
export { default as ProjectListBlock } from './projectList'
export { default as testimonialsBlock } from './testimonialBlock'
export { default as ctaBlock } from './ctaBlock'
export { default as captionsListBlock } from './captionsList'
export { default as featuredPostsBlock } from './featuredPosts'